# Generated by Django 3.2.4 on 2021-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='blogs/', verbose_name='image'),
        ),
    ]
